apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: automation-gateway-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: "semver"
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/LetsgoPens87/k8s-argo-monitoring.git"
      branch: "main"
      writeBackTarget: "kustomization:."
  applicationRefs:
    - namePattern: "automation-gateway"
      images:
        - alias: "automation-gateway"
          imageName: "dhricko9/automation-gateway:v1.x"
